all: benchmarks/src/* programs/src/*
	gcc -g benchmarks/src/PRL2D.c -o benchmarks/bin/PRL2D
	gcc -g benchmarks/src/LDC2D.c -o benchmarks/bin/LDC2D
	gcc -g benchmarks/src/RDC2D.c -o benchmarks/bin/RDC2D
	gcc -g benchmarks/src/PRL3D.c -o benchmarks/bin/PRL3D
	gcc -g benchmarks/src/LDC3D.c -o benchmarks/bin/LDC3D
	gcc -g benchmarks/src/RDC3D.c -o benchmarks/bin/RDC3D
	gcc -g programs/src/CS1.c -o programs/bin/CS1
	gcc -g programs/src/CS2.c -o programs/bin/CS2
	gcc -g programs/src/CS3.c -o programs/bin/CS3
	gcc -g programs/src/CS4.c -o programs/bin/CS4
	gcc -g programs/src/CS5.c -o programs/bin/CS5